"""add etoro id

Revision ID: 00d539030577
Revises: d6cabf03fd0b
Create Date: 2018-11-24 16:25:55.505019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d539030577'
down_revision = 'd6cabf03fd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('etoro_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'etoro_id')
    # ### end Alembic commands ###
