"""order -> orders haha

Revision ID: 31296ca966fc
Revises: e48e296913e6
Create Date: 2018-11-02 19:51:50.936069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31296ca966fc'
down_revision = 'e48e296913e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('is_long', sa.Boolean(), nullable=True),
    sa.Column('enter', sa.DateTime(), nullable=True),
    sa.Column('exit', sa.DateTime(), nullable=True),
    sa.Column('enter_price', sa.Numeric(precision=5, asdecimal=False), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=5, asdecimal=False), nullable=True),
    sa.Column('exit_PIP', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('SL', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('TP', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('opportunity_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pair_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_long', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enter', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enter_price', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True),
    sa.Column('exit_PIP', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True),
    sa.Column('units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spread', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True),
    sa.Column('SL', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True),
    sa.Column('TP', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True),
    sa.Column('opportunity_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_id', name='order_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
