"""create db

Revision ID: bfbd244e193d
Revises: 
Create Date: 2018-11-11 10:42:19.062156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbd244e193d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=64), nullable=True),
    sa.Column('units_per_pip_usd', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('comission', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('pair_id'),
    sa.UniqueConstraint('pair')
    )
    op.create_table('schema_version',
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('enter', sa.DateTime(), nullable=True),
    sa.Column('exit', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=5, asdecimal=False), nullable=True),
    sa.Column('PIP', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=True),
    sa.Column('sl', sa.Numeric(precision=7, scale=5, asdecimal=False), nullable=True),
    sa.Column('tp', sa.Numeric(precision=7, scale=5, asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.pair_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('schema_version')
    op.drop_table('pairs')
    # ### end Alembic commands ###
