"""empty message

Revision ID: e48e296913e6
Revises: 
Create Date: 2018-11-02 19:49:24.079246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48e296913e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('is_long', sa.Boolean(), nullable=True),
    sa.Column('enter', sa.DateTime(), nullable=True),
    sa.Column('exit', sa.DateTime(), nullable=True),
    sa.Column('enter_price', sa.Numeric(precision=5, asdecimal=False), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=5, asdecimal=False), nullable=True),
    sa.Column('exit_PIP', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('SL', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('TP', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('opportunity_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
